/* CREATE DEAN TABLE */ 

CREATE TABLE DEAN (
    Dean_ID VARCHAR(10),
    NIC BIGINT,
    PRIMARY KEY (Dean_ID)
);

/* CREATE FOREIGN KEY */

ALTER TABLE DEAN
ADD FOREIGN KEY (NIC) REFERENCES user(NIC);

/* INSERT DEAN DATA TO TABLE */

INSERT INTO DEAN (Dean_ID, NIC)
VALUES
('D_01', 887654321001);
